### ISSUE TITLE
Allow extending, not replacing default "FORBID_CONTENTS" list via setConfig

### ISSUE THREAD

**Issue by spaceemotion** [cure53/DOMPurify#1165]
Hi there!

We'd love to add a couple more elements to the `FORBID_CONTENTS` list. However, when passing a custom array of elements, the default list is no longer used.

There seems to be no way to get the default list either, as there's neither a default export for these, nor can I get the default list via something like DOMPurify.CONFIG....

I rather not want to copy the list into our code by hand, in case a future security updates the defaults, and we're not aware of it.

Thanks!

**Comment by cure53** [comment]
Oha, I see. Thanks for filing this. Would the issue be fixed by us making `FORBID_CONTENTS` configurable?

**Comment by cure53** [comment]
Closing this now for lack of activity, but happy to reopen

**Comment by spaceemotion** [comment]
@cure53 sorry for not seeing your reply earlier. Seems like it got lost in my inbox.

Having a way to access the default list would be good, or any kind of form of extending the current list while keeping the contents from before?

For example:

```ts
const customPurifier = DOMPurify();

customPurifier.setConfig({
  IN_PLACE: true,
  USE_PROFILES: {
    html: true,
  },
  FORBID_CONTENTS: customPurifier.config.FORBID_CONTENTS.concat([
    'custom-element',
  ],
});
```

**Comment by cure53** [comment]
Cool, I think that makes sense. Wanna spin up a PR? 🙂

**Comment by spaceemotion** [comment]
I'm wondering how to best go about this - especially in terms of security.

The easiest method would be to add a `getConfig` method that just returns `CONFIG`, but I am unsure whether that should return a new `clone()` of the config to avoid any tempering by people thinking they can do just:
```ts
purifier.getConfig().FORBID_CONTENTS.push('custom-element');
```
so basically just this?
```ts
DOMPurify.getConfig = function () {
  return CONFIG !== null ? clone(CONFIG) : null;
};

export interface DOMPurify {
  /**
   * Gets a copy of the configuration.
   *
   * @returns a clone of the current configuration, or null if the default is used.
   */
  getConfig(): Config | null;
}
```

However, that still doesn't help with getting the actual default configuration, since it's `null` unless set beforehand.

**Comment by cure53** [comment]
I would propose to amend `_parseConfig`

https://github.com/cure53/DOMPurify/blob/main/src/purify.ts#L490

This might already do the trick, first make it configurable and then use `DEFAULT_FORBID_CONTENTS` in case `cfg.FORBID_CONTENTS` is indeed not set.

**Comment by MariusRumpf** [comment]
I see two options here I think. 

1. Make `DEFAULT_FORBID_CONTENTS` externally readable in a way and use that to provide a full `cfg.FORBID_CONTENTS` as user of the library with the existing configuration option.
2. Similar to other options in the library like `cfg.ADD_ATTR`, `cfg.ADD_TAGS` a new option is added for `FORBID_CONTENTS`. With this option `cfg.ADD_FORBID_CONTENTS` the default list can be extended. Is that what you meant @cure53?

**Comment by cure53** [comment]
> Similar to other options in the library like cfg.ADD_ATTR, cfg.ADD_TAGS a new option is added for FORBID_CONTENTS. With this option cfg.ADD_FORBID_CONTENTS the default list can be extended. Is that what you meant @cure53?

I believe this is the way to go, wdyt @spaceemotion ?

**Comment by spaceemotion** [comment]
@cure53 yeah, having a new `ADD_FORBID_CONTENTS` would work just fine, too :) 

So it would basically be just this?

```ts
if (cfg.ADD_FORBID_CONTENTS) {
  if (FORBID_CONTENTS === DEFAULT_ALLOWED_TAGS) {
    FORBID_CONTENTS = clone(FORBID_CONTENTS);
  }

  addToSet(FORBID_CONTENTS, cfg.ADD_FORBID_CONTENTS, transformCaseFunc);
}
```

**Comment by cure53** [comment]
Yep, that plus maybe 1-2 tests should get us places 🙂

**Comment by cure53** [comment]
Thanks a ton 😄 @spaceemotion does that PR solve your issue?

**Comment by spaceemotion** [comment]
Yup, it should! Will check with the new version then :)
